# Generated by Django 6.0.7 on 2026-07-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('career_category', models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('ENGINEERING', 'Engineering'), ('BUSINESS', 'Business & Finance'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('ARTS', 'Arts & Design'), ('LAW', 'Law'), ('SOCIAL_SCIENCE', 'Social Science'), ('SCIENCE', 'Science'), ('HOSPITALITY', 'Hospitality & Tourism'), ('AGRICULTURE', 'Agriculture'), ('OTHER', 'Other')], max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('future_scope', models.TextField(blank=True)),
                ('minimum_education_level', models.CharField(choices=[('SEE', 'SEE'), ('PLUS_TWO', '+2'), ('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD')], max_length=20)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='NPR', max_length=10)),
                ('salary_note', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='careers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
