# Generated by Django 6.0.7 on 2026-07-22 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_assessmentoption_is_correct'),
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAttributeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_weights', to='assessment.assessmentattribute')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_weights', to='careers.career')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('career', 'attribute'), name='unique_career_attribute')],
            },
        ),
    ]
