# Generated by Django 6.0.7 on 2026-07-23 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_careerattributeweight'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_courses', to='careers.career')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_courses', to='courses.course')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('career', 'course'), name='unique_career_course')],
            },
        ),
    ]
