# Generated by Django 6.0.7 on 2026-07-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_careercategory_career_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='job_demand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='career',
            name='skills_required',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='career',
            name='work_environment',
            field=models.TextField(blank=True),
        ),
    ]
