# Generated by Django 6.0.7 on 2026-07-16 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessmentquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('option_code', models.CharField(max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessment.assessmentquestion')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('question', 'option_code'), name='unique_option_code_per_question')],
            },
        ),
    ]
