# Generated by Django 6.0.7 on 2026-07-16 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_assessmentoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_scores', to='assessment.assessmentattribute')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessment.assessmentoption')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('option', 'attribute'), name='unique_option_attribute_score')],
            },
        ),
    ]
