# Generated by Django 6.0.7 on 2026-07-17 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_studentanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttributeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_scores', to='assessment.assessmentattempt')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='assessment.assessmentattribute')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'attribute'), name='one_attribute_score_per_attempt')],
            },
        ),
    ]
