# Generated by Django 6.0.7 on 2026-07-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_studentattributescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='section',
            field=models.CharField(choices=[('INTEREST', 'Interests'), ('TRAIT', 'Natural Strengths'), ('WORK_STYLE', 'Work Style'), ('VALUE', 'Values'), ('APTITUDE', 'Aptitude')], default='INTEREST', max_length=20),
            preserve_default=False,
        ),
    ]
