# Generated by Django 6.0.7 on 2026-07-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_assessmentquestion_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentoption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
