# Generated by Django 6.0.7 on 2026-07-23 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_courses', to='colleges.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_courses', to='courses.course')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('college', 'course'), name='unique_college_course')],
            },
        ),
    ]
