# Generated by Django 6.0.7 on 2026-07-24 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_collegecourse'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colleges', to='locations.district'),
        ),
        migrations.AddField(
            model_name='college',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colleges', to='locations.province'),
        ),
    ]
