# Generated by Django 6.0.7 on 2026-07-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_college_address_college_district_college_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='ownership',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('COMMUNITY', 'Community')], default='PRIVATE', max_length=20),
        ),
    ]
