# Generated by Django 6.0.7 on 2026-07-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('short_name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('duration_years', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[('SEE', 'SEE'), ('PLUS_TWO', '+2'), ('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD')], max_length=20)),
                ('entry_requirement', models.CharField(choices=[('SEE', 'SEE'), ('PLUS_TWO', '+2'), ('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
