# Generated by Django 6.0.7 on 2026-07-16 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_education_level', models.CharField(blank=True, choices=[('SEE', 'SEE'), ('PLUS_TWO', '+2'), ('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor')], max_length=20)),
                ('highest_education_institution', models.CharField(blank=True, max_length=255)),
                ('academic_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('budget_range', models.CharField(blank=True, choices=[('BELOW_2_LAKHS', 'Below NPR 2 Lakhs'), ('TWO_TO_FOUR', 'NPR 2–4 Lakhs'), ('FOUR_TO_SIX', 'NPR 4–6 Lakhs'), ('SIX_TO_EIGHT', 'NPR 6–8 Lakhs'), ('ABOVE_8', 'Above NPR 8 Lakhs')], max_length=30)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='locations.district')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='locations.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
