# Generated by Django 6.0.7 on 2026-07-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='highest_education_level',
            field=models.CharField(blank=True, choices=[('SEE', 'SEE'), ('PLUS_TWO', '+2'), ('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD')], max_length=20),
        ),
    ]
